name: Update README

on:
  schedule:
    # Every day at 09:17 KST
    - cron: '17 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    name: Update this repo's README with latest blog posts

    steps:
      - uses: actions/checkout@v7
      - uses: gautamkrishnar/blog-post-workflow@1.9.7
        with:
          feed_list: 'https://soulee.dev/rss.xml'
          max_post_count: 5
